{
  "uid" : "21cc5df2c6abd4ee",
  "name" : "TestBatchModifyFlies.test_batch_modify_files[pause_offer_error]",
  "title" : "Test batch modify files [pause_offer_error]",
  "time" : {
    "start" : 1560319742345,
    "stop" : 1560319751528,
    "duration" : 9183
  },
  "summary" : {
    "attachments" : 4,
    "steps" : 0
  },
  "failure" : {
    "message" : "Exception: 用例关联文件不存在\n文件路径： pause_offer.json",
    "stackTrace" : "test_name = 'pause_offer_error', param = 'pause_offer.json'\n_path = '/Users/wangjuan/workpace/Aff_service/aff/pages/offer', relevance = None\n\n    def read_param(test_name, param, _path, relevance=None):\n        \"\"\"\n        读取用例中参数parameter\n        :param test_name: 用例名称\n        :param param: parameter\n        :param relevance: 关联对象\n        :param _path: case路径\n        :param result: 全局结果\n        :return:\n        \"\"\"\n    \n        if isinstance(param, dict):\n            param = replace(param, relevance)\n        elif isinstance(param, list):\n            param = replace(param, relevance)\n        else:\n            try:\n>               with open(_path + \"/\" + param, \"r\", encoding=\"utf-8\") as f:\nE               FileNotFoundError: [Errno 2] No such file or directory: '/Users/wangjuan/workpace/Aff_service/aff/pages/offer/pause_offer.json'\n\nbin/unit/readParameter.py:30: FileNotFoundError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_postBatchModifyFlies.TestBatchModifyFlies object at 0x112b9c048>\ncase_data = {'address': '/admin/offer/postBatchModifyFlies', 'check': [{'check_type': 'entirely_check', 'expected_code': 200, 'expected_request': 'result_pause_offer.json'}], 'cookies': True, 'file': True, ...}\n\n    @pytest.mark.parametrize(\"case_data\", case_dict[\"test_case\"],\n                             ids=[\"pause_offer_error\", \"pause_offer_schedule\"])\n    @allure.story(\"batch_modify_offer\")\n    @pytest.mark.flaky(reruns=3, reruns_delay=3)\n    def test_batch_modify_files(self, case_data):\n        \"\"\"\n    \n        :param case_data: 测试用例\n        :return:\n        \"\"\"\n        self.init_relevance = ini_request(case_dict, PATH)\n        # 发送测试请求\n>       api_send_check(case_data, case_dict, self.init_relevance, PATH)\n\naff/testcase/test_postBatchModifyFlies.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nbin/unit/apiSendCheck.py:23: in api_send_check\n    project_dict[\"test_info\"].get(\"address\"), _path, relevance)\nbin/unit/apiSend.py:31: in send_request\n    parameter = readParameter.read_param(data[\"test_name\"], data[\"parameter\"], _path, relevance)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ntest_name = 'pause_offer_error', param = 'pause_offer.json'\n_path = '/Users/wangjuan/workpace/Aff_service/aff/pages/offer', relevance = None\n\n    def read_param(test_name, param, _path, relevance=None):\n        \"\"\"\n        读取用例中参数parameter\n        :param test_name: 用例名称\n        :param param: parameter\n        :param relevance: 关联对象\n        :param _path: case路径\n        :param result: 全局结果\n        :return:\n        \"\"\"\n    \n        if isinstance(param, dict):\n            param = replace(param, relevance)\n        elif isinstance(param, list):\n            param = replace(param, relevance)\n        else:\n            try:\n                with open(_path + \"/\" + param, \"r\", encoding=\"utf-8\") as f:\n                    data = json.load(f)\n                    for i in data:\n                        if i[\"test_name\"] == test_name:\n                            param = i[\"parameter\"]\n                            break\n                    if not isinstance(param, dict):\n                        raise Exception(\"未能找到用例关联的参数\\n文件路径：%s\\n索引：%s\" % (param, _path))\n                    else:\n                        param = replace(param, relevance)\n            except FileNotFoundError:\n>               raise Exception(\"用例关联文件不存在\\n文件路径： %s\" % param)\nE               Exception: 用例关联文件不存在\nE               文件路径： pause_offer.json\n\nbin/unit/readParameter.py:41: Exception"
  },
  "description" : {
    "value" : "\n\n        :param case_data: 测试用例\n        :return:\n        ",
    "type" : "TEXT"
  },
  "severity" : "NORMAL",
  "status" : "FAILED",
  "testId" : null,
  "suite" : {
    "uid" : "f0ed89dd652314b4",
    "name" : "test_postBatchModifyFlies",
    "title" : "Test post batch modify flies"
  },
  "steps" : [ ],
  "attachments" : [ {
    "title" : "Captured log call",
    "source" : "ccb8e53a-3783-4f0b-996e-48ba2454ab0f-attachment.txt",
    "type" : "text/plain",
    "size" : 348,
    "uid" : "30a61ca8704d210b"
  }, {
    "title" : "Captured log call",
    "source" : "1e3968c9-c068-4ec4-978d-c9e65c15ead9-attachment.txt",
    "type" : "text/plain",
    "size" : 348,
    "uid" : "4c7c4a5513fe5744"
  }, {
    "title" : "Captured log call",
    "source" : "96ee253f-e607-4783-98b8-ce8c8c8c0be2-attachment.txt",
    "type" : "text/plain",
    "size" : 348,
    "uid" : "3ced248933c69b09"
  }, {
    "title" : "Captured log call",
    "source" : "156ff886-7992-4455-873a-9097cdc615c5-attachment.txt",
    "type" : "text/plain",
    "size" : 348,
    "uid" : "2b9f476a2b4ef41c"
  } ],
  "issues" : [ ],
  "labels" : [ {
    "name" : "thread",
    "value" : "41942-MainThread"
  }, {
    "name" : "suite-name",
    "value" : "test_postBatchModifyFlies"
  }, {
    "name" : "feature",
    "value" : "offer"
  }, {
    "name" : "story",
    "value" : "batch_modify_offer"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "suite-title",
    "value" : null
  }, {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "host",
    "value" : "xiaoxideMacBook-Pro.local"
  }, {
    "name" : "language",
    "value" : "cpython3"
  } ],
  "parameters" : [ ]
}